# Generated by Django 6.0.2 on 2026-03-14 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=120, unique=True)),
                ('model_type', models.CharField(choices=[('HIGH_END', 'High End'), ('LOW_END', 'Low End')], max_length=32)),
                ('hardware_requirement', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('provider', models.CharField(default='huggingface', max_length=64)),
                ('temperature', models.FloatField(default=0.1)),
                ('max_tokens', models.PositiveIntegerField(default=350)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'model_type', 'model_name'],
            },
        ),
    ]
