# Generated by Django 6.0.2 on 2026-03-14 21:20

import utils.file_utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to=utils.file_utils.document_upload_path)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=32)),
                ('file_type', models.CharField(blank=True, max_length=32)),
                ('is_scanned', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('processing_log', models.TextField(blank=True)),
                ('processing_progress', models.PositiveSmallIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
                ('vector_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
