# Generated by Django 6.0.2 on 2026-03-14 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(db_index=True, max_length=64)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
