# Generated by Django 6.0.2 on 2026-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
